### ISSUE TITLE
Some kind of network error?

### ISSUE THREAD

**Issue by TomHarkness** [fidesmo/fdsm#17]
When trying to load an applet to a fidesmo card I get the following.

tomharkness@ThMini:~$fidesmo --install Fidesmo/out/ExampleCardlet.cap
Using $FIDESMO_APP_ID: 31fc2b99
Using card in ACS ACR122U PICC Interface
Using $FIDESMO_APP_ID: 31fc2b99

API error: HTTP/1.1 502 Bad Gateway
The server was acting as a gateway or proxy and received an invalid response from the upstream server.

**Comment by TomHarkness** [comment]
If I upload it first using --upload:

tomharkness@ThMini:~$fidesmo --install Fidesmo/out/ExampleCardlet.cap
Using $FIDESMO_APP_ID: 31fc2b99
Using card in ACS ACR122U PICC Interface
Using $FIDESMO_APP_ID: 31fc2b99
Delivering: Install application A0000006170031FC2B9901
Session ID: 2ec3aa6f-3040-4d3e-9192-24f4b7975164
Failure: Could not install A0000006170031FC2B99

**Comment by martinpaljak** [comment]
The fact that you get 502 without --upload is bad documentation that should be fixed ASAP. Debugging why installation fails, please re-run with --trace-apdu

**Comment by TomHarkness** [comment]
Yes I realise that there is almost no documentation for this tool yet. 

Here is the output with trace apdu:

`tomharkness@ThMini:~$fidesmo --install Fidesmo/out/ExampleCardlet.cap --trace-apdu
Using $FIDESMO_APP_ID: 31fc2b99
SCardConnect("ACS ACR122U PICC Interface", T=*) -> T=1, 3B88800146494445534D4F3167
A>> T=1 (4+0000) 00A40400
A<< (0102+2) (71ms) 6F648408A000000151000000A5589F6501FF9F6E06479120813B00734906072A864886FC6B01600B06092A864886FC6B020202630906072A864886FC6B03640B06092A864886FC6B040255650B06092B8510864864020103660C060A2B060104012A026E0102 9000
A>> T=1 (4+0000) FFCA0000 00
A<< (0004+2) (2ms) 2F4BD113 9000
A>> T=1 (4+0000) 80CA9F7F
A<< (0045+2) (44ms) 9F7F2A47905075479120813B007272013466988216481272790000000017300631333436360000000000000000 9000
A>> T=1 (4+0000) 00CA0042
A<< (0007+2) (23ms) 31045100000108 9000
A>> T=1 (4+0000) 00CA0045
A<< (0007+2) (23ms) 00005A2F4BD113 9000
A>> T=1 (4+0011) 00A40400 0B A000000617020002000002
A<< (0013+2) (27ms) 420300005A4306023967FE8B41 9000
A>> T=1 (4+0011) 00A40400 0B A000000617020002000001
A<< (0022+2) (32ms) 41040000000242010243010045040000000244020300 9000
Using card in ACS ACR122U PICC Interface
Using $FIDESMO_APP_ID: 31fc2b99
Delivering: Install application A0000006170031FC2B9901
Session ID: 51677b2b-b3a1-4523-86df-19633ad929bd
A>> T=1 (4+0000) 00A40400 00
A<< (0102+2) (71ms) 6F648408A000000151000000A5589F6501FF9F6E06479120813B00734906072A864886FC6B01600B06092A864886FC6B020202630906072A864886FC6B03640B06092A864886FC6B040255650B06092B8510864864020103660C060A2B060104012A026E0102 9000
A>> T=1 (4+0008) 80500100 08 D4AF30F61690043E 00
A<< (0028+2) (68ms) 0000727201346698821601020007C5794B593432A1DB576CF9518779 9000
A>> T=1 (4+0016) 84820300 10 4E8141A5C0D245197110DA43D81BD7EE
A<< (0000+2) (63ms) 9000
A>> T=1 (4+0016) 84F21002 10 0E11ADD6F82D758C6A246CCF03B647A6 00
A<< (0056+2) (81ms) E3174F07A00000015153509F7001018408A000000151535041E31D4F0AA00000061702000200019F700101840BA000000617020002000101 9000
A>> T=1 (4+0016) 84F24002 10 0E11ADD6F82D758CBE1F0BCB30EB2CA6 00
A<< (0065+2) (88ms) E3144F0BA0000006170200020000019F700107C50100E3144F0BA0000006170200020000029F700107C50100E3134F0AA0000006170131FC2B999F70010FC50180 9000
A>> T=1 (4+0040) 84E60200 28 DF13A78C3B6009FF4DAC0E611D30E0F35F67BF80B35BEEF6C613B4530AC9DB76F2A9FBE274942540 00
A<< (0001+2) (82ms) 00 9000
A>> T=1 (4+0248) 84E80000 F8 5C9CE2C7F1C7835D9BC37BD8A2137993F3B651E3E386C73766BCEC1873E56C1C7E323D21C899B4AFE9B3619F069A83F1100EE375E12184387CF5F32B7967FE8B8B425E199A70118A28DDE7116168A73308303DA08EE29A832CB35E28DBEBD3FAFABEC142423AA8C2B582CC5DAF5AE4FBE4EC6D5238E3AF759F30DFAA23E56C7124E2DD6B83DBFE005C36EF6DCC09B0E1E0A9D4134C33BCD3733A19E96DF88B02ABDA21DF6452EA28C960B4D873532B76432173B0F3D253C6CFD067AA250FBF636818D752D2A5E8AEE38B3B3F1653D2C30D55A82CB6713FA38D7E890CB0657CE76DE48FC56A79078AE1BDBD47C9C3E820297D339466E5D617 00
A<< (0000+2) (1s509ms) 6A80
A>> T=1 (4+0176) 84E88001 B0 E6518DC5421213D626BA7FC719C9D58576A8D59155B5F8E2C2849216F8B34C77F25E360117871CFB025C13FCF8F29CFC93ACFE28BB0798CB4DA02E801CA4A6C4456AA4C7F309BA94F3629AA6D6D8163B18B0616EBE6D95869B7532479B8AEE33F35713E50AA2137A6C3FE1E992D5EA67A1A8CD51BCC93AA66AAC69B39E358ADB0C7DE001FF34F9FBF16B4A2A97D871DB7A4E9D25B38CBDC8B324B432370E40DD7006C9C130150563027184619042A0A3 00
A<< (0000+2) (132ms) 6985
A>> T=1 (4+0056) 84E60C00 38 DF13A78C3B6009FF57B751B8CFC8CBE2F0E9F1CEE40EB5AA43FA81B1696D2D5AFB33B0E4C7E5E21B328F13C517DD0A9AA0F5A5767FDB3624 00
A<< (0000+2) (88ms) 6A88
Failure: Could not install A0000006170031FC2B99`

**Comment by martinpaljak** [comment]
What is the content of the card before installation?

> fdsm --card-apps

What is the capfile about?

> java -jar capfile.jar Fidesmo/out/ExampleCardlet.cap

**Comment by TomHarkness** [comment]
Card had nothing installed.

Cap file was the example from the developer  tutorial. 

I managed to  get it working after a few more attempts.

**Comment by martinpaljak** [comment]
Which JC SDK did you target

**Comment by TomHarkness** [comment]
2.2.2. JDK 1.8 . Under OS X

**Comment by TomHarkness** [comment]
Able to compile cap files with Ant build tasks, install to the Fidesmo card using the fdsm utility but with the HelloFidesmo example applet and test utility jcard v2.2.2 and jdk . 1.8 I get the following response from the card:

tom@SilverBox:~/Fidesmo/out/production/Fidesmo$ java helloTest.HelloFidesmoTest
Terminals: [PC/SC terminal ACS ACR122U PICC Interface]
Answer to SELECT APDU: ResponseAPDU: 2 bytes, SW=6a82

I think it's mostly user error and lack of knowledge about the fidesmo platform / javacard that's causing my issues.

**Comment by TomHarkness** [comment]
This has been resolved - user error. Needed to compile against jdk 8 on OS X. The repo above is now updates and working cleanly.

**Comment by martinpaljak** [comment]
FYI: the need to use --upload will soon be removed, and the "user error" cases not happen.

**Comment by martinpaljak** [comment]
This was fixed in #57 and will be released shortly
