### ISSUE TITLE
Update your FDSM notice

### ISSUE THREAD

**Issue by Franzaine** [fidesmo/fdsm#18]
When trying to deliver a service on the Fidesmo platform (testing tools / CCM install) I got a 500 internal server error. But this could of course happen because of any other error as well. It was resolved by updating to a later version of FDSM but it would be nice if there'd be a more helpful error message if a problem might be resolved by updating. Maybe add a check if there are subsequent releases and tell the user if there are any?

**Comment by martinpaljak** [comment]
Fixed by #22
