### ISSUE TITLE
Request: Don't require a cap file for uninstall command

### ISSUE THREAD

**Issue by BrianHVB** [fidesmo/fdsm#19]
The procedure for uninstalling an applet from a card seems to only require the application ID and application key. But the FDSM tool also requires that a .cap file is provided. The cap file does not have to match the application ID for the uninstall to be successful. (e.g. as long as you know the id and key, you can provide any random cap file).

When designing/testing an app it is not uncommon to overwrite the cap file after the applet has been installed, so it is good that these applets can still be uninstalled after the original cap file is gone. However, the documentation and semantics of the uninstall command do not make this clear.

**Comment by martinpaljak** [comment]
As the application ID (not just the appId, but the full AID) is not "visible" from the card, the logical unit to operate with seems to be a CAP file, that contains that information.` --uninstall` is the reverse of `--install` 

There's another issue with the API, delete operations never fail ("if X is not on the card, it must have been already deleted, so success"), which gives the impression that you can give any CAP file for arguments (as long as it has the right AID prefix).

I'm a bit reluctant to change the CAP file oriented approach, as the install/uninstall pair seems about right granularity.

Do you have strong requirements or arguments for changes? We could add DWIM: if the argument to `--uninstall` looks like an AID, we try to delete that.

**Comment by BrianHVB** [comment]
I don't think I have any really strong arguments for not requiring the cap file in light of your explanation. I was coming at it more from the expected semantics of "uninstall" as it relates to software in general, as opposed to specifically in JavaCard. In the general context, you load/execute a binary file to install something, but don't need to use that binary to uninstall it.

I also have been using FDSM almost exclusively in conjunction with ant-javacard, where I would set the appId in a configuration file then not really think about it again. Since FDSM is specific to Fidesmo, the prefix portion of the AID is a constant, but without the cap file, there would be no way for FDSM to know what suffix was used. Based on your response, I'm assuming that the full AID, including any custom suffix, is a) required to uninstall an applet, and b) can't be retrieved from the card. Given those constraints, it makes sense to require the cap file.

I think my only request at this point would be to update the FDSM's `--help` output to convey that the original cap file is not required to remove an applet. It can be a little worrying to delete the cap file with a `clean`, then realize that you forgot to uninstall the applet first.

**Comment by martinpaljak** [comment]
Fixed since d60b574b
