### ISSUE TITLE
The card-apps command does not list the installed applets for the VivoKey Flex One.

### ISSUE THREAD

**Issue by BrianHVB** [fidesmo/fdsm#20]
Tested on 19.01.31 and 19.01.16

When running `java -jar fdsm.jar --card-apps` on the VivoKey Flex One (JCOP3SECIDCS ), the result is always *No applications*, even after an applet has been successfully installed from a cap file.

When running the same command on the Fidesmo reference card (JCOP24R2), any applets installed from cap files are listed, but apps installed via `--run <appId>` or via the Fidesmo Android app are not.

For both cards, the Fidesmo Android app correctly lists applets installed via cap file (fdsm), service recipie (fdsm), or Fidesmo app.

```
Using card in Feitian R502 0
CIN: 0E4880-0471400A BATCH: 000059 UID: 0471400A0E4880
OS type: JCOP3SECIDCS (platfrom v2)
Using card in Feitian R502 0
No applications
```

![smartselect_20190216-200427_fidesmo](https://user-images.githubusercontent.com/17414903/52907830-b5197000-3226-11e9-827f-384b14250729.jpg)

**Comment by martinpaljak** [comment]
Thank you for the report! This will be fixed with #23
