### ISSUE TITLE
Suppress update notification for Maven dependency versions of fdsm-tool

### ISSUE THREAD

**Issue by rileyg98** [fidesmo/fdsm#68]
We're using fdsm-tool via a Maven dependency in our own provisioning workflow and I notice we get the update notification to upgrade to v21.04.12 - no such version is on Maven, though (we're using the only public version, v21.04.06)

Would a flag to suppress this notification be possible?

**Comment by martinpaljak** [comment]
The same rationale as with #69 applies: fdsm-tool is a cli tool, intended to be used as one. If you want to have a dependency on the library portion of it, have a dependency on `fdsm` and use the classes from there. Another option is to apply `--offline` option or just to ignore the notification
