### ISSUE TITLE
System.exit in dependency library

### ISSUE THREAD

**Issue by rileyg98** [fidesmo/fdsm#69]
As per another issue raised, we use this in a dependency through Maven. I noticed that fdsm's Main calls System.exit() upon finishing the requested service, which requires a janky work-around using Security Providers to block when being called from another Java program. This is not recommended practice for libraries that are used as dependencies (in fact, some see it as broken behaviour).

**Comment by martinpaljak** [comment]
fdsm consists of two parts: a library part and a cli tool part. The cli tool part is not intended to be used as a dependency or be called from another codebase via methods other than a usual process via Runtime.exec() or similar.
