### ISSUE TITLE
NullPointerException when the program starts 

### ISSUE THREAD

**Issue by luisrodero-fidesmo** [fidesmo/fdsm#79]
Got `NullPointerException` when running the program:
```
$ java -jar fdsm.jar --help
Exception in thread "main" java.lang.NullPointerException
	at com.fidesmo.fdsm.Main.main(Main.java:69)
```

Also, I'd advice to update README so it warns that `JAVA_HOME` must be set.

**Comment by JSantosP** [comment]
Already fixed with latest release (https://github.com/fidesmo/fdsm/releases/tag/v22.04.08)

**Comment by luisrodero-fidesmo** [comment]
Checked, command in issue description works with latest version :+1:
