### ISSUE TITLE
No developer accounts anymore?

### ISSUE THREAD

**Issue by tx-fidesmo** [fidesmo/fdsm#82]
Your link points to developer.fidesmo.com but this just redirects to fidesmo.com.
On the page the API is described and more.
But nowhere there's a chance to create a developer account.

**Comment by acvigue** [comment]
I'm experiencing this issue as well. How do we create a developer account?

**Comment by cegg1** [comment]
I would like to create a developer account. Could you please help? 
Thanks

**Comment by martinpaljak** [comment]
The README needs updating - no "open for everyone" accounts but obviously all potential partners can see how it works and experiment. You'd need to contact sales@ or use http://www.fidesmo.com/helpme

**Comment by acvigue** [comment]
> The README needs updating - no "open for everyone" accounts but obviously all potential partners can see how it works and experiment. You'd need to contact sales@ or use http://www.fidesmo.com/helpme

Thanks, I am just replying to add some context. I was able to resolve my issue by reaching out through that email.

**Comment by sergkh** [comment]
Readme has been updated with new links. So closing this issue.
